### ISSUE TITLE
How to subscribe / unsuscribe with Mod + Shift?

### ISSUE THREAD

**Issue by system32uwu** [rickbutton/workspacer#210]
From reading the source code I though I could do the following:

**workspacer.config.csx**
```c#
context.Keybinds.Unsubscribe(mod | Keys.LShiftKey, Keys.O);
```
But that throws the following error:

```
Microsoft.CodeAnalysis.Scripting.CompilationErrorException: (63,34): error CS0019: Operator '|' cannot be applied to operands of type 'KeyModifiers' and 'Keys'
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.ThrowIfAnyCompilationErrors(DiagnosticBag diagnostics, DiagnosticFormatter formatter)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.CreateExecutor[T](ScriptCompiler compiler, Compilation compilation, Boolean emitDebugInformation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, Func`2 catchException, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.RunAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at workspacer.ConfigHelper.DoConfig(IConfigContext context)
   at workspacer.workspacer.Start()
   at workspacer.Program.Run()
   at workspacer.Program.Main(String[] args)
```

**Comment by flyxyz123** [comment]
try this:
```
KeyModifiers mod = KeyModifiers.Alt;
context.Keybinds.Unsubscribe(mod | KeyModifiers.LShift, Keys.O);
```

**Comment by system32uwu** [comment]
Yup I got it after reading the source again, thanks
