### ISSUE TITLE
Crash when launching new window

### ISSUE THREAD

**Issue by scottopell** [rickbutton/workspacer#24]
```
---------------------------
unhandled exception!
---------------------------
System.NullReferenceException: Object reference not set to an instance of an object.

   at Workspacer.Workspace.DoLayout()

   at Workspacer.WorkspaceManager.SwitchToPreviousWorkspace()

   at Workspacer.KeybindManager.DoKeyboardEvent(Keys key, KeyModifiers modifiersPressed)

   at Workspacer.KeybindManager.Hook(Int32 nCode, UIntPtr wParam, IntPtr lParam)

press ctrl-c to copy this
---------------------------
OK   
---------------------------

```

**Comment by scottopell** [comment]
Getting this seemingly randomly. Can't be sure of what I'm doing when it comes up.

```
---------------------------
unhandled exception!
---------------------------
System.NullReferenceException: Object reference not set to an instance of an object.

   at Workspacer.Workspace.DoLayout()

   at Workspacer.WorkspaceManager.SwitchToPreviousWorkspace()

   at Workspacer.KeybindManager.DoKeyboardEvent(Keys key, KeyModifiers modifiersPressed)

   at Workspacer.KeybindManager.Hook(Int32 nCode, UIntPtr wParam, IntPtr lParam)

press ctrl-c to copy this
---------------------------
OK   
---------------------------

```

**Comment by scottopell** [comment]
Interestingly this seems to be a non-fatal error. I can continue using workspacer as expected as long as I don't hit "OK" on this dialog

**Comment by rickbutton** [comment]
@scottopell is this still happening?

**Comment by rickbutton** [comment]
can't reproduce anymore, closing
