### ISSUE TITLE
Crash with unknown PID

### ISSUE THREAD

**Issue by scottopell** [rickbutton/workspacer#39]
```
---------------------------
unhandled exception!
---------------------------
System.ArgumentException: Process with an Id of 7804 is not running.

   at System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName)

   at workspacer.WindowsWindow.get_Process()

   at workspacer.WindowRouter.<>c.<.ctor>b__3_4(IWindow window)

   at workspacer.WindowRouter.RouteWindow(IWindow window, IWorkspace defaultWorkspace)

   at workspacer.WorkspaceManager.AddWindow(IWindow window, Boolean switchToWorkspace, Boolean firstCreate)

   at workspacer.WindowsManager.RegisterWindow(IntPtr handle, Boolean emitEvent)

press ctrl-c to copy this
---------------------------
OK   
---------------------------
```

This occurred when I clicked on an application as workspacer was starting up.

I saw the application flash black briefly, so maybe internally it like swapped itself out for a new process or something strang?

**Comment by rickbutton** [comment]
this should be resolved in the latest unstable release
