### ISSUE TITLE
Exception on gvim "diff"

### ISSUE THREAD

**Issue by scottopell** [rickbutton/workspacer#46]
As soon as a trigger a diff in gvim, I get this exception:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at workspacer.WindowRouter.<>c.<.ctor>b__3_0(IWindow window)
   at workspacer.WindowRouter.RouteWindow(IWindow window, IWorkspace defaultWorkspace)
   at workspacer.WorkspaceManager.AddWindow(IWindow window, Boolean switchToWorkspace, Boolean firstCreate)
   at workspacer.WindowsManager.RegisterWindow(IntPtr handle, Boolean emitEvent)
```

I think this is some kind of race condition similar to #39 because I believe gvim shells out to command line diff

**Comment by rickbutton** [comment]
you are likely correct, accessing `IWindow.Process` is failing here.

breaking change time! accessing `IWindow.Process` is brittle, so I'm removing it. Instead, I added the remaining thing-you-might-need from the `Process` object, `IWindow.ProcessId`. This might break your config, but if you move to the new `Process{Thing}` properties for your filters/routes, this issue will go away.

The fix for this is pushed in `0.9.5.94`
