### ISSUE TITLE
Exception when waking up laptop

### ISSUE THREAD

**Issue by scottopell** [rickbutton/workspacer#47]
```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at workspacer.WorkspaceManager.InitializeWithState(WorkspaceState state, IEnumerable`1 allWindows)
   at workspacer.workspacer.Start()
   at workspacer.Program.Run()
   at workspacer.Program.Main(String[] args)
```

**Comment by rickbutton** [comment]
good catch, this was happening because workspace saves a small json blob of "state" before a restart, and it was not accounting for added monitors across restarts anymore. the `WorkspaceManager` would try to access the `MonitorsToWorkspaces` entries for the new monitors, but the state didn't have it, so crash. this is fixed in `0.9.5.93`. re-open if the fix didn't work
